name       : supertux
version    : 0.6.0
release    : 4
source     :
    - https://github.com/SuperTux/supertux/releases/download/v0.6.0/SuperTux-v0.6.0-Source.tar.gz : c4c3e5fa6f90e87b8c5ad6b22a179e9a9839bf997e7f219e22bbcd1c97223ac0
license    : GPL-3.0-or-later
component  : games.platformer
summary    : SuperTux is a jump'n'run game with strong inspiration from the Super Mario Bros
description: |
    SuperTux is a jump'n'run game with strong inspiration from the Super Mario Bros.
builddeps  :
    - pkgconfig(SDL2_image)
    - pkgconfig(freetype2)
    - pkgconfig(gl)
    - pkgconfig(glew)
    - pkgconfig(libcurl)
    - pkgconfig(openal)
    - pkgconfig(vorbis)
    - libboost-devel
    - physfs-devel
setup      : |
    sed -i "s/games\/supertux2/supertux2/" CMakeLists.txt

    %cmake -DCMAKE_BUILD_TYPE=Release \
        -DINSTALL_SUBDIR_BIN=bin \
           .
build      : |
    %make
install    : |
    %make_install
