name       : supertux
version    : 0.4.0
release    : 1
source     :
    - git|git://github.com/SuperTux/supertux.git : v0.4.0
license    : GPL-3.0
component  : games.platformer
summary    : SuperTux is a jump'n'run game with strong inspiration from the Super Mario Bros.
description: |
    SuperTux is a jump'n'run game with strong inspiration from the Super Mario Bros.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(glew)
    - pkgconfig(libcurl)
    - pkgconfig(ogg)
    - pkgconfig(openal)
    - pkgconfig(sdl2)
    - pkgconfig(SDL2_image)
    - pkgconfig(vorbis)
    - libboost-devel
    - physfs-devel
    - git
setup      : |
    sed -i "s/games\/supertux2/supertux2/" CMakeLists.txt
    %cmake -DCMAKE_BUILD_TYPE=RELEASE -DINSTALL_SUBDIR_BIN=bin \
           .
build      : |
    %make
install    : |
    %make_install
