name       : supertux
version    : 0.6.2
release    : 10
source     :
    - https://github.com/SuperTux/supertux/releases/download/v0.6.2/SuperTux-v0.6.2-Source.tar.gz : 26a9e56ea2d284148849f3239177d777dda5b675a10ab2d76ee65854c91ff598
homepage   : https://www.supertux.org/
license    : GPL-3.0-or-later
component  : games.platformer
summary    : SuperTux is a jump'n'run game with strong inspiration from the Super Mario Bros
description: |
    SuperTux is a jump'n'run game with strong inspiration from the Super Mario Bros.
builddeps  :
    - pkgconfig(SDL2_image)
    - pkgconfig(freetype2)
    - pkgconfig(gl)
    - pkgconfig(glew)
    - pkgconfig(libcurl)
    - pkgconfig(openal)
    - pkgconfig(vorbis)
    - libboost-devel
    - physfs-devel
setup      : |
    sed -i "s/games\/supertux2/supertux2/" CMakeLists.txt
    %cmake -DCMAKE_BUILD_TYPE=Release \
           -DINSTALL_SUBDIR_BIN=bin \
           .
build      : |
    %make
install    : |
    %make_install
